project:
  type: website
  output-dir: docs

website:
  title: "STA380 Course Webpage"
  navbar:
    right:
      - href: home.qmd
        text: "Home"
      - text: "Course Information"
        menu:
        - href: pages/outline.qmd
          text: "Course Outline"
        - href: pages/syllabus.qmd
          text: "Syllabus"
        - href: pages/coursefor.qmd
          text: "Who This Course is For"
      - href: pages/agenda.qmd
        text: "Agenda"
      - href: pages/lectures.qmd
        text: "Lectures"
      - href: pages/tutorial.qmd
        text: "Tutorials"
      - href: pages/test.qmd
        text: "Tests & Quizzes"
      - text: "Project"
        menu:
        - href: pages/project/project_outline.qmd
          text: "Project Overview"
        - href: pages/project/group_formation.qmd
          text: "Group Formation"
        - href: pages/project/proposal.qmd
          text: "Proposal"
        - href: pages/project/basic_imp.qmd
          text: "Basic Implementation Check"
        - href: pages/project/package_comp.qmd
          text: "Package Compiling"
        - href: pages/project/website.qmd
          text: "Website Prototype"
        - href: pages/project/final_website.qmd
          text: "Final Implementation"
      - text: "Other"
        menu: 
        - href: pages/other/ref.qmd
          text: "Reference Letters"
        - href: pages/other/reading.qmd
          text: "Research Information"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
